### ISSUE TITLE
"Can't get 1" Error

### ISSUE THREAD

**Issue by itscory** [motoxnate/El-Disk-Utility#2]
When executed, the below message displays and the script does not run as expected.

> Title: Can't get 1.
> Message: Finder got an error: Can't get 1. (-1728)

![screen shot 2015-11-17 at 5 35 07 pm](https://cloud.githubusercontent.com/assets/11150244/11227044/a12a015e-8d51-11e5-80c6-c8bfb574a786.png)

I'm looking into it.
## Test Environment

Hardware:

> Model Name:    MacBook Air
> Model Identifier:  MacBookAir6,2
> Processor Name:    Intel Core i5
> Processor Speed:   1.4 GHz
> Number of Processors:  1
> Total Number of Cores: 2
> L2 Cache (per Core):   256 KB
> L3 Cache:  3 MB
> Memory:    4 GB
> Boot ROM Version:  MBA61.0099.B21
> SMC Version (system):  2.13f15

Software:

> System Version:    OS X 10.11.1 (15B42)
> Kernel Version:    Darwin 15.0.0
> Boot Volume:   Macintosh HD
> Boot Mode: Normal

**Comment by itscory** [comment]
The error displays after the first line is read. The first line asks Finder to find...

> the name of every disk whose local volume is true and startup is false

So "can't get 1" probably means finder was unable to get a result. So I plugged in a USB drive and ran it, and the script works as expected. Since my SSD drive has the _startup_ attribute, it does not satisfy these conditions.

@motoxnate, is this script meant to work with all disks or only disks not running OS X?

**Comment by motoxnate** [comment]
Good call. This script will work with all volumes, I was just trying not to include the startup volume because obviously erasing it would be bad and not possible. I think the 'startup false' flag should be removed and implemented later in the program to prevent users from trying to modify the startup volume.

**Comment by itscory** [comment]
Perhaps the script should have a "protectStartup" boolean. When the user tries to modify the startup volume and the variable is true (by default), it will warn the user about the dangers and asks if s/he would like to continue. If yes, it makes protectStartup false and won't prompt the user again until the script ends.

On another note, .scpt files are not very good with git since they are not plaintext; They are similar to word documents where the editor saves the file in its own weird format, unreadable by git which makes it hard to track history. Do you mind if I do [what this guy suggested](http://stackoverflow.com/questions/7641806/how-would-you-put-an-applescript-script-under-version-control) and export it as a plaintext file called main.applescript?

**Comment by motoxnate** [comment]
That definitely sounds like a good idea to add a boolean. If you want to give it a shot go for it!
Definitely! I'm new to GitHub so I just uploaded what I had. If you have something else that works better feel free to do it.

Also, this is just an idea but I figured I would throw it out there. I would love to recreate the disk utility interface using Xcode. I'm not very familiar with it, but if anyone else is and would like to give it a go, feel free.
If not I'll get around to it sooner or later. :smiley:

**Comment by itscory** [comment]
I am kinda new to it too. But yes, I was not able to find an alternative to Disk Utility that is open-source or free. So this is in demand and needs to happen. I'm no professional, but I've got [some experience in XCode](https://itunes.apple.com/us/app/frequencies-sounds-only-teens/id398296783), but I am much less familiar with diskutil. My experience with diskutil is limited to `diskutil list` to find the location of volumes so I know where to dd to when I need to make a bootable USB drive. Otherwise I use Disk Utility, which is now weird, ugly, and doesn't have the `DUDebugMenuEnabled` default anymore so it can't show me my hidden partitions! What the heck?! 
`</rant>`

Sorry, I'm starting to love using Markdown. Yes, I'd love to help make an XCode version. How about after fixing and releasing the script, we start a new branch for an XCode project? And we keep the name because, I have to say, that is one badass name.

**Comment by motoxnate** [comment]
Love the enthusiasm! Sounds like a plan. 
Gotta say the name sure works XD

**Comment by itscory** [comment]
Would you mind adding me as a collaborator? [This link](https://github.com/motoxnate/El-Disk-Utility/settings/collaboration) should get you to the page that lets you do it.

**Comment by motoxnate** [comment]
Done!

**Comment by itscory** [comment]
Thanks! I prefer not talking through Issues. Can I get your email? I'll delete your comment after I see it so you don't get too many emails from a Nigerian Prince. Or you can get fancy and use [this website](https://www.igolder.com/pgp/encryption/) (or GPGTools if you're familiar with it) to encrypt it using [my PGP key](http://pgp.mit.edu/pks/lookup?op=get&search=0xCB6FDB6A3674B9B2) before sending.

**Comment by motoxnate** [comment]
Sure!
Its motoxnate788@gmail.com <mailto:motoxnate788@gmail.com>
No worries, just delete the comment once you see it haha
